global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: gateway
  honor_labels: true
  static_configs:
  - targets: ['nrod:8000', 'rabbitmq:15692', 'darwin:8000', 'darwin_rti:8000']
