{
 "title": "Open Rail Data Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Train Movement Messages Rate AVG/Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_train_mvt_msg_count_total[3m]) * 60",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "NROD Avg. rates, per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_inbound_message_count_total[3m]) * 60",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "NROD S-Class Message AVG Rate/Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_s_class_message_count_total[3m]) * 60",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "NROD C-Class Message AVG rate/minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_c_class_message_count_total[3m]) * 60",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "RMQ Delivery  Rates AVG/Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Message Rates" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_rmq_delivery_stats_total[3m])",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "TD Area Message Rates AVG/Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(nrod_td_area_count_total[3m]) * 60",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Inbound NROD message latency",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Latency(seconds)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(inbound_message_latency_bucket[3m]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}